### ISSUE TITLE
Need to support "upload as data" in local test server

### ISSUE THREAD

**Issue by brimoor** [voxel51/platform-sdk#13]
The local test server needs to support analytics that use the `upload_as_data: True` option. The expected behavior is that the file(s) should be written to the output folder where everything else is written.

This is a bug unless we are giving a helpful error message that says "this feature is not yet supported"

**Comment by brimoor** [comment]
This is a bug. Two bugs actually. The error message that one gets is an error message _about_ the error message. Stack trace below:
```
Uncaught exception
Traceback (most recent call last):
  File "main.py", line 82, in main
    task_manager.upload_output_as_data("test", video_path)
  File "/engine/platform-sdk/voxel51/platform/task.py", line 224, in upload_output_as_data
    name, output_path, self.task_config, self.task_status)
  File "/engine/platform-sdk/voxel51/platform/task.py", line 620, in upload_output_as_data
    task_config.job_id, output_path)
  File "/engine/platform-sdk/voxel51/platform/api.py", line 138, in upload_job_output_as_data
    _validate_response(res)
  File "/engine/platform-sdk/voxel51/platform/api.py", line 183, in _validate_response
    raise APIError.from_response(res)
  File "/engine/platform-sdk/voxel51/platform/api.py", line 171, in from_response
    message = _parse_json_response(res)["error"]["message"]
KeyError: 'error'
```
